# Generated by Django 4.1 on 2022-08-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                ("city", models.CharField(max_length=120, verbose_name="City")),
                ("county", models.CharField(max_length=120, verbose_name="County")),
                (
                    "street_name",
                    models.CharField(max_length=120, verbose_name="Street Name"),
                ),
                ("street_number", models.IntegerField(verbose_name="Street Number")),
                ("floor", models.IntegerField(verbose_name="Floor")),
                ("bulding_info", models.IntegerField(verbose_name="Building Info")),
                (
                    "apartment_number",
                    models.IntegerField(verbose_name="Apartment Number"),
                ),
                ("zip_code", models.CharField(max_length=15, verbose_name="Zip Code")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="contact Phone"
                    ),
                ),
                ("web", models.URLField(blank=True, verbose_name="Website Address")),
                (
                    "email_address",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email Address"
                    ),
                ),
            ],
        ),
    ]
