# Generated by Django 4.1 on 2022-08-13 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0002_alter_contact_bulding_info"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact", old_name="bulding_info", new_name="building_info",
        ),
    ]
